Vagrant.configure("2") do |config|
    config.vm.define "vm1" do |vm1|
        vm1.vm.box = "debian/bullseye64"
        vm1.vm.hostname = 'apache.local'
        vm1.vm.network "public_network", type: "dhcp"
        config.vm.provider "virtualbox" do |vbox|
            vbox.name = "apache"
            vbox.gui = false
            vbox.cpus = 2
            vbox.memory = 2048
            vbox.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
        end
    end
end

